const mainStyle = { padding: 32, fontFamily: "system-ui" } as const;

export default function HomePage() {
  return (
    <main style={mainStyle}>
      <h1>BrowserAgent</h1>
      <p>Generated by platform-scaffold. Edit <code>src/app/page.tsx</code> to start.</p>
      <ul>
        <li>Gateway: http://localhost:8080</li>
        <li>API:     http://localhost:8001</li>
        <li>AI:      http://localhost:8002</li>
      </ul>
    </main>
  );
}
